# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
R: 
  - 3.6.1
  - 3.6.3
  - oldrel
  - release
cache: packages
warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
